# Generated by Django 4.2.3 on 2023-10-19 15:31

from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criação'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='estoque'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(default='static/images/icone_pizza.jpeg', force_min_size=False, upload_to='produtos', variations={'thumb': (124, 124)}, verbose_name='imagem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='preco'),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
    ]
