# Generated by Django 4.2.3 on 2023-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_ativo_produto_criado_produto_estoque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15, verbose_name='usuario')),
                ('senha', models.CharField(max_length=10, verbose_name='senha')),
            ],
        ),
    ]
