# Generated by Django 4.2.3 on 2023-11-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='confirmacao_senha',
            field=models.CharField(default='', max_length=10, verbose_name='confirmacao de senha'),
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='', max_length=20, verbose_name='e-mail'),
        ),
    ]
